# Generated by Django 4.1.6 on 2023-03-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rathing',
            new_name='reit_com',
        ),
    ]
